"""empty message

Revision ID: 08b0a246eb19
Revises: ca242096c6b1
Create Date: 2022-07-14 10:51:02.271602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b0a246eb19'
down_revision = 'ca242096c6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('active_status', sa.Boolean(), server_default=sa.text('1'), nullable=True))
    op.add_column('subscriber', sa.Column('del_status', sa.Boolean(), server_default=sa.text('1'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'del_status')
    op.drop_column('subscriber', 'active_status')
    # ### end Alembic commands ###
