"""empty message

Revision ID: ca242096c6b1
Revises: 
Create Date: 2022-07-14 10:46:18.337726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca242096c6b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('active_status', sa.Boolean(), nullable=False))
    op.add_column('subscriber', sa.Column('del_status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'del_status')
    op.drop_column('subscriber', 'active_status')
    # ### end Alembic commands ###
